#
# To use your own pub key:
# export PUBLICKEY=`cat ~/.ssh/id_rsa.pub`
#
version: '3'

services:

  biocache-store:
    build:
      context: .
    image: vertigoala/biocache-store
    environment:
      - BIOPWD=biocache
#      - PUBLICKEY
#      - USETTYD=true
      # JAVA DEBUG OPTIONS
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - "2022:22"
      - "7681:7681"
      - "5005:5005"
    volumes:
      # JAVA DEBUG: mount classes at "/usr/bin/biocache/etc" (already on classpath)
      - ./target/classes:/usr/lib/biocache/etc
    depends_on:
      - cassandradb

  cassandradb:
    image: cassandra:3.11.4
    ports:
      - "9042:9042"
    volumes:
      - ./conf/cassandra3-schema.txt:/docker-entrypoint-initdb.d/cassandra3-schema.cql
      - ./scripts/cassandra-entrypoint.sh:/cassandra-entrypoint.sh
    entrypoint:
      - bash
      - -c
      - source /cassandra-entrypoint.sh
